# Generated by Django 5.1 on 2025-01-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=355)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('motivation', models.CharField(max_length=355)),
            ],
        ),
    ]
