# Generated by Django 5.1.6 on 2025-02-10 18:11

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_private', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('hide_connection_list', models.BooleanField(default=False)),
                ('hide_followers_list', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('skills_description', models.TextField(blank=True, max_length=2500, null=True)),
                ('interests_description', models.TextField(blank=True, max_length=2500, null=True)),
                ('currently_working_on', models.TextField(blank=True, max_length=2500, null=True)),
                ('check_in_cycle_length', models.CharField(choices=[('12h', '12 hours'), ('1D', '1 day (24 hours)'), ('2D', '2 days (48 hours)'), ('3D', '3 days (72 hours)'), ('5D', '5 days'), ('1W', '1 week (7 days)')], default='2D', max_length=255)),
                ('bio', models.CharField(blank=True, default='', max_length=350, null=True)),
                ('by_line', models.CharField(default='-', max_length=60)),
                ('date_of_birth', models.DateField(validators=[users.models.Profile.validate_age])),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, default='default_pfp.jpg', null=True, upload_to='media/profile_pics')),
                ('visible_to_search', models.BooleanField(default=False)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('blocked', models.ManyToManyField(blank=True, related_name='blocked_users', to=settings.AUTH_USER_MODEL)),
                ('do_not_show', models.ManyToManyField(blank=True, related_name='do_not_show_users', to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(blank=True, related_name='my_followers', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('restricted', models.ManyToManyField(blank=True, related_name='restricted_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
