# Generated by Django 5.1.6 on 2025-02-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentknowledgesource',
            name='label',
            field=models.CharField(blank=True, max_length=455, null=True),
        ),
    ]
